# Generated by Django 2.2.5 on 2019-09-28 10:00

from django.db import migrations, models
import osr.static.python.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SudokuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, storage=osr.static.python.storage.OverwriteStorage(), upload_to='.')),
            ],
        ),
    ]
