# Generated by Django 2.2.5 on 2019-10-01 19:08

from django.db import migrations, models
import osr.static.python.storage


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokumodel',
            name='image',
            field=models.ImageField(blank=True, storage=osr.static.python.storage.OverwriteStorage(), upload_to='uploads/'),
        ),
    ]
